#!/usr/bin/env ruby

require "eveveneno_palindrome"

lines = File.readlines("phrases.txt")
lines.each do |line|
    if line.palindrome?
        puts "palindrome detected: #{line}"
    end
end

palindromes = lines.select(&:palindrome?)
File.write('palindrome_file.txt', palindromes.join)
