#!/usr/bin/env ruby
require "open-uri"
require "nokogiri"

# Returns the paragraphs from a URL link, stripped of reference numbers.
# Especially useful for text-to-speech (both native and foreign).

if !ARGV.empty?
    url = ARGV.shift
    doc = Nokogiri::HTML(URI.open(url)) # Parse with Nokogiri
    doc.css('.reference').each(&:remove)
    puts doc.css('p').map(&:content).join("\n\n")
else
    abort ("Aborted - please provide a URL link as an argument.")
end